# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('town', models.CharField(max_length=50, verbose_name='town')),
            ],
            options={
                'verbose_name': 'farmer',
                'verbose_name_plural': 'farmers',
            },
        ),
    ]
